### ISSUE TITLE
Fix Event table wrapping on mobile

### ISSUE THREAD

**Issue by sdaniels6363** [sdaniels6363/bootcamp-project-1#15]

**Comment by atifrabbani1** [comment]
Event table wrapping thing has also been fixed.
Had to change the <th> to <td>. Applied the class on the <tr> containing all these <td>. And change the font to bold in css.

I have already commited the changes I made to flight one. Let me know if it is ok to commit the changes for the event table wrapping too. As I am using john_final_tweaks branch.

**Comment by sdaniels6363** [comment]
If you think you have it squared away, go ahead and commit it, so we can test.  Thanks for jumping on this, was going to look at it after I got all of my other stuff squared away.

**Comment by atifrabbani1** [comment]
Changes pushed. You can check now.

**Comment by sdaniels6363** [comment]
Issue looks to be resolved, thanks Atif!
